# Tên ứng dụng
spring.application.name=student-management

spring.datasource.url=jdbc:postgresql://ep-old-silence-a1arm48g-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner
spring.datasource.password=${NEON_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Báo cho Hibernate biết đang dùng PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Tự động tạo bảng nếu chưa có, và giữ nguyên dữ liệu
spring.jpa.hibernate.ddl-auto=update