# Tên ứng dụng
spring.application.name=student-management

spring.datasource.url=jdbc:postgresql://localhost:5432/student_db
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Báo cho Hibernate biết đang dùng PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Tự động tạo bảng nếu chưa có, và giữ nguyên dữ liệu
spring.jpa.hibernate.ddl-auto=update