# Tên ứng dụng
spring.application.name=student-management

# Cấu hình file Database SQLite (tự động tạo file student.db tại thư mục gốc project)
spring.datasource.url=jdbc:sqlite:student.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Cấu hình JPA/Hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false